"use client"

// Imports
import { SessionProvider } from "next-auth/react"
import { Lato, Playfair_Display_SC } from "next/font/google";

// Local Imports
import Header from "@/components/organisms/Header";

// Styles
import "./globals.css";
import styles from './layout.module.css'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const font__body = Lato({
  variable: "--font__body",
  subsets: ["latin"],
  weight: "400"
});

const font__headers = Playfair_Display_SC({
  variable: "--font__headers",
  subsets: ["latin"],
  weight: "400"
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {


  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Pennywise" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${font__body.variable} ${font__headers.variable}`}>

        <SessionProvider>
          <Header />
          <main className={styles.main}>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
