"use client"

import { SessionProvider } from "next-auth/react"
import { Inter, Roboto_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/Header";

const inter = Inter({
  variable: "--font__Body",
  subsets: ["latin"],
  weight: "400"
});

const font__robotoSerif = Roboto_Serif({
  variable: "--font__Headers",
  subsets: ["latin"],
  weight: "700"
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Pennywise" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${inter.variable} ${font__robotoSerif.variable}`}>

        <SessionProvider>
        <Header />
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
