-- AlterTable
ALTER TABLE "Bill" ALTER COLUMN "paid" SET DEFAULT false,
ALTER COLUMN "incurredAt" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL,
ALTER COLUMN "paid" SET DEFAULT false;

-- AlterTable
ALTER TABLE "FoodBudget" ALTER COLUMN "paid" SET DEFAULT false,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Income" ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL;
